Controllers/PartialsController.cs
using klassycafe.DataAccess;
using klassycafe.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace klassycafe.Controllers
{
    public class PartialsController : Controller
    {
        ChefDataAccess chefDA = new ChefDataAccess();
        ContactDataAccess contactDA = new ContactDataAccess();
        MenuItemDataAccess menuItemDA = new MenuItemDataAccess();
        MenuCategoryDataAccess menuCategoryDA = new MenuCategoryDataAccess();

        public ActionResult _Footer()
        {
            CONTACT contact = contactDA.Get();
            return PartialView(contact);
        }

        public ActionResult _TopSlider()
        {
            return PartialView();
        }

        public ActionResult _AboutUs()
        {
            return PartialView();
        }

        public ActionResult _MenuSlider()
        {
            List<MENUITEM> sliderItems = menuItemDA.GetForMenuSlider();
            return PartialView(sliderItems);
        }

        public ActionResult _Chefs()
        {
            List<CHEF> chefs = chefDA.GetActives();
            return PartialView(chefs);
        }

        public ActionResult _Reservation()
        {
            CONTACT contact = contactDA.Get();
            return PartialView(contact);
        }

        public ActionResult _ReservationForm()
        {
            return PartialView();
        }

        public ActionResult _Menu()
        {
            List<MENUCATEGORY> mcs = menuCategoryDA.GetActives();
            List<MENUITEM> mis = menuItemDA.GetActives();

            return PartialView(new MENUINDEX() { CATEGORIES = mcs, ITEMS = mis });
        }
    }
}

Views/Shared/_AccountLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ziya Çetinkaya">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
    <title>Klassy Cafe - Admin</title>
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/font-awesome.css">
    <link rel="stylesheet" href="~/Content/assets/css/templatemo-klassy-cafe.css">
    <link rel="stylesheet" href="~/Content/assets/css/owl-carousel.css">
    <link rel="stylesheet" href="~/Content/assets/css/lightbox.css">
</head>

<body>
    <div class="container">
        @RenderBody()
    </div>

    <!-- jQuery -->
    <script src="~/Content/assets/js/jquery-2.1.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="~/Content/assets/js/popper.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="~/Content/assets/js/owl-carousel.js"></script>
    <script src="~/Content/assets/js/accordions.js"></script>
    <script src="~/Content/assets/js/datepicker.js"></script>
    <script src="~/Content/assets/js/scrollreveal.min.js"></script>
    <script src="~/Content/assets/js/waypoints.min.js"></script>
    <script src="~/Content/assets/js/jquery.counterup.min.js"></script>
    <script src="~/Content/assets/js/imgfix.min.js"></script>
    <script src="~/Content/assets/js/slick.js"></script>
    <script src="~/Content/assets/js/lightbox.js"></script>
    <script src="~/Content/assets/js/isotope.js"></script>

    <!-- Global Init -->
    <script src="~/Content/assets/js/custom.js"></script>
</body>
</html>

Views/Shared/_AdminLayout.cshtml
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
    <link href="~/Content/admin_assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/admin_assets/css/style.css" rel="stylesheet" />
    <link href="~/Content/assets/css/font-awesome.css" rel="stylesheet" type="text/css">
    <title>Klassy Cafe - Admin</title>
</head>
<body>
    <div class="container">
        <div class="row mb-2 py-4">
            <div class="col-12 text-center">
                <img src="~/Content/assets/images/klassy-logo.png" class="mb-3" />
                <p class="m-0 p-0"><strong>Welcome</strong> @Session["UserName"] </p><a href="/logout" class="btn btn-sm btn-danger">Logout</a>
            </div>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Klassy Cafe</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item px-2">
                            <a class="nav-link text-light" href="/admin">HOME</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link text-light" href="/reservations">RESERVATIONS</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link text-light" href="/menu-items">MENU ITEMS</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link text-light" href="/chefs">CHEFS</a>
                        </li>
                        <li class="nav-item px-2">
                            <a class="nav-link text-light" href="/contact-info">CONTACT INFO</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        @RenderBody()
    </div>
    <script src="~/Content/admin_assets/js/bootstrap.bundle.min.js"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Ziya Çetinkaya">
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600;700&display=swap" rel="stylesheet">
    <title>Klassy Cafe</title>
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="~/Content/assets/css/font-awesome.css">
    <link rel="stylesheet" href="~/Content/assets/css/templatemo-klassy-cafe.css">
    <link rel="stylesheet" href="~/Content/assets/css/owl-carousel.css">
    <link rel="stylesheet" href="~/Content/assets/css/lightbox.css">
</head>

<body>
    <div id="preloader">
        <div class="jumper">
            <div></div>
            <div></div>
            <div></div>
        </div>
    </div>
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <a href="index.html" class="logo">
                            <img src="~/Content/assets/images/klassy-logo.png" alt="klassy cafe html template">
                        </a>
                        <ul class="nav">
                            <li class="scroll-to-section"><a href="#top" class="active">Home</a></li>
                            <li class="scroll-to-section"><a href="#about">About</a></li>
                            <li class="scroll-to-section"><a href="#preferences">Chefs' Preferences</a></li>
                            <li class="scroll-to-section"><a href="#chefs">Chefs</a></li>
                            <li class="scroll-to-section"><a href="#menu">Menu</a></li>
                            <li class="scroll-to-section"><a href="#reservation">Contact Us</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    @RenderBody()

    @Html.Action("_Footer", "Partials")    

    <!-- jQuery -->
    <script src="~/Content/assets/js/jquery-2.1.0.min.js"></script>

    <!-- Bootstrap -->
    <script src="~/Content/assets/js/popper.js"></script>
    <script src="~/Content/assets/js/bootstrap.min.js"></script>

    <!-- Plugins -->
    <script src="~/Content/assets/js/owl-carousel.js"></script>
    <script src="~/Content/assets/js/accordions.js"></script>
    <script src="~/Content/assets/js/datepicker.js"></script>
    <script src="~/Content/assets/js/scrollreveal.min.js"></script>
    <script src="~/Content/assets/js/waypoints.min.js"></script>
    <script src="~/Content/assets/js/jquery.counterup.min.js"></script>
    <script src="~/Content/assets/js/imgfix.min.js"></script>
    <script src="~/Content/assets/js/slick.js"></script>
    <script src="~/Content/assets/js/lightbox.js"></script>
    <script src="~/Content/assets/js/isotope.js"></script>

    <!-- Global Init -->
    <script src="~/Content/assets/js/custom.js"></script>
    <script>

        $(function () {
            var selectedClass = "";
            $("p").click(function () {
                selectedClass = $(this).attr("data-rel");
                $("#portfolio").fadeTo(50, 0.1);
                $("#portfolio div").not("." + selectedClass).fadeOut();
                setTimeout(function () {
                    $("." + selectedClass).fadeIn();
                    $("#portfolio").fadeTo(50, 1);
                }, 500);

            });
        });

    </script>
</body>
</html>